### ISSUE TITLE
Is this current 'enough' to install in 2019?

### ISSUE THREAD

**Issue by Strykar** [yesday/odroid-c2-archlinux-luks#1]
I see the last update was in Sep 2017.
As Arch is rolling release, would you say it's worth trying to download, flash and update today?

Any chance of a new release?

**Comment by g000444555** [comment]
Hi,

Unfortunately, I won't be creating a new release in the foreseeable future and haven't been testing the image lately.

If you want to try to download, flash and update today, I would recommend re-generating the initramfs as described in: [instructions](https://yesday.github.io/blog/2017/how-to-install-archlinux-with-full-disk-encryption-on-odroid-c2.html#generate_new_initramfs_and_reboot_into_the_luks_rootfs )This is because if the kernel version has changed then the initramfs has to be updated.

Another solution, which is not as easy as flushing the image, is to follow the instructions from https://yesday.github.io/blog/2017/how-to-install-archlinux-with-full-disk-encryption-on-odroid-c2.html in order to create your own image.

I hope that helps.

Thank you

**Comment by yesday** [comment]
Hi,

Unfortunately, I won't be creating a new release in the foreseeable future and haven't been testing the image lately.

If you want to try to download, flash and update today, I would recommend re-generating the initramfs as described in: [instructions](https://yesday.github.io/blog/2017/how-to-install-archlinux-with-full-disk-encryption-on-odroid-c2.html#generate_new_initramfs_and_reboot_into_the_luks_rootfs ) This is because if the kernel version has changed then the initramfs has to be updated.

Another solution, which is not as easy as flushing the image, is to follow the instructions from https://yesday.github.io/blog/2017/how-to-install-archlinux-with-full-disk-encryption-on-odroid-c2.html in order to create your own image.

I hope that helps.

Thank you
